version: '3.8'

services:
  finance-tracker:
    build: .
    container_name: finance-tracker
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./finance_tracker.db:/app/finance_tracker.db
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - PORT=5000 